### ISSUE TITLE
Gives error if no babel or webpack plugins are used

### ISSUE THREAD

**Issue by ishan28mkip** [vimcaw/craco-fast-refresh#1]
/Users/ishan/skillbee-related/skillbee-frontend/node_modules/craco-fast-refresh/index.js:9
      cracoConfig.babel.plugins.push(ReactRefreshBabelPlugin);
                        ^

TypeError: Cannot read property 'plugins' of undefined

**Comment by ishan28mkip** [comment]
Added webpack-bundle-analyzer to analyse which files are taking the maximum size
Added CracoAntDesignPlugin to add custom less file definition in antd

**Comment by ishan28mkip** [comment]
CracoAntDesignPlugin also removes unnecessary antd includes, adding purgecss to remove any other unused css

**Comment by vimcaw** [comment]
Thank your feedback, it has fixed in [1.0.2 (release)](https://github.com/vimcaw/craco-fast-refresh/releases/tag/1.0.2).
