### ISSUE TITLE
__webpack_require__ error

### ISSUE THREAD

**Issue by kharenzze** [vimcaw/craco-fast-refresh#5]
Hi! First of all, nice work and thank you for creating this package.

Something is not working properly in my case. When my app starts, it throws an error:

![image](https://user-images.githubusercontent.com/5865128/96440607-80826680-1208-11eb-8e48-72ddd00acf5a.png)

Looks like an error importing react-responsive. When I remove the craco-fast-refresh from craco.config.js, it works perfectly. Maybe I'm missing some configuration step.

Also I saw this warning: 
```
warning "craco-fast-refresh > @pmmmwh/react-refresh-webpack-plugin@0.4.2" has unmet peer dependency "webpack@>=4.43.0 <6.0.0".
```

I see react-scripts 3.4.3 comes with webpack 4.42.0. I've tried upgrading to webpack 4.44.0 but the error is also thrown.
I tested both node v12 and v14 latest builds

**Comment by vimcaw** [comment]
I think this should be related to https://github.com/pmmmwh/react-refresh-webpack-plugin, [craco-fast-refresh](https://github.com/vimcaw/craco-fast-refresh) just added two configs to `craco.config.js` (and make a little other things): 

```
// Configure Babel plugin
cracoConfig.babel.plugins.push(ReactRefreshBabelPlugin);
// Configure Webpack plugin
cracoConfig.webpack.plugins.push(new ReactRefreshWebpackPlugin());
```

**Comment by vimcaw** [comment]
Maybe you should post an issue to [pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin).

**Comment by kharenzze** [comment]
Yeah, that makes sense. BTW after a quick look to react-refresh-webpack-plugin I see that `new HotModuleReplacementPlugin()` should be also added to webpack plugins array. Maybe it can be related to my issue. What do you think @vimcaw ?

**Comment by vimcaw** [comment]
`create-react-app` has done this, so we don't need to add it again.

You can output all `webpack` plugins in `craco.config.js`: 

```
module.exports = () => {
  return {
    webpack: {
      configure: webpackConfig => {
        console.log(webpackConfig.plugins);
        throw -1;
      },
    },
    plugins: [{ plugin: fastRefreshCracoPlugin }],
  };
};
```

**Comment by vimcaw** [comment]
Here is it: 

![](https://user-images.githubusercontent.com/21964227/96444599-1803ab80-1241-11eb-9216-1d25e58f5a8d.png)

**Comment by kharenzze** [comment]
Thanks for the info! Then I'll check issues in ReactRefreshWebpackPlugin repo and I'll let you know if I discover something related

**Comment by kharenzze** [comment]
I investigated this issue, and it doesn't seem to be related to this repo. Code is pretty clear. I'm closing the issue here and continue investigating to get the solution
